apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: aws-cli
spec:
  description: This task performs operations on Amazon Web Services resources using aws.
  params:
    - default: aws $@
      description: The AWS script to run
      name: SCRIPT
      type: string
    - default:
        - help
      description: AWS cli arguments to be passed
      name: ARGS
      type: array
  steps:
    - args:
        - $(params.ARGS)
      image: >-
        docker.io/amazon/aws-cli:2.0.52@sha256:1506cec98a7101c935176d440a14302ea528b8f92fcaf4a6f1ea2d7ecef7edc4
      name: awscli
      resources: {}
      script: $(params.SCRIPT)
  workspaces:
    - name: source
      optional: true
    - mountPath: /tekton/home/.aws
      name: secrets
      optional: true
