kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: init-container-build
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: STORAGE_CLASS
  volumeMode: Filesystem
