apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-init-container
spec:
  params:
    - default: 's3://models/TIMESTAMP/model.data'
      name: S3_OBJECT_URL
      type: string
    - default: 'http://minio-service.minio.svc.cluster.local:9000'
      name: S3_ENDPOINT_URL
      type: string
    - default: 'https://github.com/mamurak/AI-for-edge-microshift-demo.git'
      name: git_repository_url
      type: string
    - default: 'REGISTRY/REPOSITORY/IMAGE:TAG'
      name: target_image_url
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.git_repository_url)
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:55b0686bbd045c9c77820686318f8a5ff2aff06de566b067f408d27a93bf153c
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: init-container-build-space
    - name: download-model
      params:
        - name: SCRIPT
          value: |-
            mkdir ~/.aws
            cp /tekton/home/.aws/credentials ~/.aws
            aws configure list
            aws s3 cp $1 $2 --endpoint-url $3
        - name: ARGS
          value:
            - $(params.S3_OBJECT_URL)
            - /workspace/source/init-container/model.data
            - $(params.S3_ENDPOINT_URL)
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: aws-cli
      workspaces:
        - name: source
          workspace: init-container-build-space
        - name: secrets
          workspace: s3-parameters
    - name: buildah
      params:
        - name: IMAGE
          value: $(params.target_image_url)
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:23fb7971ea6ac4aaaaa1139473a602df0df19222a3b5a76b551b2b9ddd92e927
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: /workspace/source/init-container/Containerfile
        - name: CONTEXT
          value: /workspace/source/init-container
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: '--platform linux/arm64/v8'
      runAfter:
        - download-model
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: init-container-build-space
  workspaces:
    - name: init-container-build-space
    - name: s3-parameters