kind: Secret
apiVersion: v1
metadata:
  name: aws-connection-models
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'true'
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: models
stringData:
  AWS_ACCESS_KEY_ID: ACCESS_KEY
  AWS_DEFAULT_REGION: us-east-1
  AWS_S3_BUCKET: models
  AWS_S3_ENDPOINT: S3_ENDPOINT
  AWS_SECRET_ACCESS_KEY: SECRET_KEY
type: Opaque
