kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "Face recognition Elyra"
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image enabling computer vision use cases, in particular face recognition.
  name: face-recognition-elyra
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: 'true'
    opendatahub.io/notebook-image: 'true'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "1.1.0"
      from:
        kind: DockerImage
        name: quay.io/mmurakam/face-recognition-notebook:face-recognition-notebook-v1.1.0
      importPolicy: {}
      referencePolicy:
        type: Local
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"opencv","version":"4.6.0.66"},{"name":"face-recognition","version":"1.3.0"},{"name":"elyra","version":"3.14.1"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"3.8"}]'
