kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: registry
  annotations:
    volume.kubernetes.io/selected-node: jetson
  namespace: registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: kubevirt-hostpath-provisioner
